### ISSUE TITLE
Pulse Inspector UI is broken

### ISSUE THREAD

**Issue by marco-c** [taskcluster/taskcluster-tools#231]
![immagine](https://user-images.githubusercontent.com/1616846/27806791-f23ed834-603c-11e7-808d-5d3f3b1efbce.png)

**Comment by eliperelman** [comment]
@marco-c do you have any details about the parameters or bindings you used to produce this?

**Comment by marco-c** [comment]
Any exchange and routing key pattern seem to have the same effect.
For example, exchange/taskcluster-queue/v1/task-group-resolved and #.

**Comment by eliperelman** [comment]
@marco-c interesting, I don't seem to replicate. I wonder if this is a caching issue with the old site. Could you hard refresh/clear your cache, and try it again? If that doesn't work, could you post some details about browser versions, etc.?

**Comment by marco-c** [comment]
I can still reproduce after clearing the cache. I'm using the latest Nightly on Linux.

**Comment by eliperelman** [comment]
@marco-c ah ok, I think I may have found where this lies. I'll have a fix for you shortly.

**Comment by eliperelman** [comment]
@marco-c ok, should be fixed in production, sorry about that!

**Comment by marco-c** [comment]
Thanks!
