### ISSUE TITLE
Weird error message in task-inspector

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/taskcluster-tools#257]
@helfi92 any ideas:
https://screenshots.firefox.com/NMKsbGPwBI01JrR8/tools.taskcluster.net

link: https://screenshots.firefox.com/NMKsbGPwBI01JrR8/tools.taskcluster.net

> rail-afk> recently I have noticed that some tasks give me a 404-like error in the UI, even though they should be there, the error message contains the status. example: https://tools.taskcluster.net/groups/LJDnka8tTtOOdlm6-S1vFw/tasks/uBwIJZ77QgSah9sxsacppg/details
19:03 <rail-afk> any idea what is going on?
19:05 <rail-afk> I've seen this for tasks submitted via the old scheduler API and via in-tree scheduling 

Maybe it has to do with the fact that the task doesn't have any runs yet...

**Comment by jonasfj** [comment]
Credits to @escapewindow for finding this..

**Comment by escapewindow** [comment]
Itym @rail :)

**Comment by jonasfj** [comment]
Lol, sorry I mixed up rail and aki :)
