### ISSUE TITLE
Logins reset page state

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-tools#261]
The process of using tools used to be:
 * Navigate to the edit page, make changes, click a button
 * Get an error because you're not logged in
 * Login (page changes to show login)
 * Click the button again

Now, logging in resets the page to its default status based on the route, deleting all of the information I had entered.

**Comment by eliperelman** [comment]
I don't think this is the case for all pages, but there could be some where we blindly reset things if any props change, which credentials could be a part of on those pages.

**Comment by eliperelman** [comment]
We should re-investigate this now that the new AuthController has landed.

**Comment by djmitche** [comment]
I was mildly careful in adjusting that that *most* pages now only update if the new UserSession and the old satisfy `UserSession.userChanged`, which should roughly correspond to a sign-in or sign-out event.

I don't remember which page I saw this on originally.  I think we can close it for now and I'll re-open if i see it again.

Also, Auth0 (now that it actually renews!) will help by not making people login as often.
