### ISSUE TITLE
Follow log doesn't work

### ISSUE THREAD

**Issue by franziskuskiefer** [taskcluster/taskcluster-tools#275]
Ticking the follow log box in "Run Logs" unticks itself when the log is updated.

**Comment by eliperelman** [comment]
Hmm, I don't seem to replicate. Did you happen to scroll the container by chance?

**Comment by djmitche** [comment]
I think this occurs when the log finishes, and it reloads lazy_backing.log.

**Comment by eliperelman** [comment]
Ah ok, I see the problem.

**Comment by franziskuskiefer** [comment]
Is this in production yet? I still have the same issue.

**Comment by eliperelman** [comment]
@franziskuskiefer this particular patch is, but if you are still experiencing this, could you please provide more details about the circumstances, or possibly steps to replicate? Thanks.

**Comment by franziskuskiefer** [comment]
Take for example task [LhS8sZkcSJu3bb3_h6uUsQ](https://tools.taskcluster.net/groups/LhS8sZkcSJu3bb3_h6uUsQ/tasks/LhS8sZkcSJu3bb3_h6uUsQ/runs/0/logs/public%2Flogs%2Flive.log). Looking at the Run Logs tab and setting the Follow log doesn't work for me (you can retrigger it to test). The follow log tick disappears every time the run log content is scrolled.
So another test case is just enabling follow log and then scrolling the log. This disables follow log.

**Comment by eliperelman** [comment]
This is expected. We purposefully shut off the following of the log if you scroll it since if you scroll, you are desiring to not be kept at the bottom of the log.

**Comment by franziskuskiefer** [comment]
Ok, but it's also disabled when I click it the first time and it jumps down to the bottom.

**Comment by franziskuskiefer** [comment]
![follow-log](https://user-images.githubusercontent.com/890105/29316558-c8b8a5dc-81c8-11e7-9d38-322ee905916a.gif)

**Comment by eliperelman** [comment]
@franziskuskiefer can you provide details on what browser, version, and OS you are using?

**Comment by franziskuskiefer** [comment]
This is Firefox Nightly (any recent version) on Arch Linux x64.

**Comment by gregarndt** [comment]
I have experienced this with both Nightly and DevEdition but not on Chrome.  it seems that as the log is streaming the box can't be selected at all.  If the log is slowly streaming (some pauses in between chunks), it looks like I can select the checkbox, it will follow that current chunk displayed, but when new text is rendered the checkbox is unchecked and it stops following

**Comment by helfi92** [comment]
@franziskuskiefer Has the issue been resolved?

**Comment by franziskuskiefer** [comment]
I think so. It's working for me now.

**Comment by helfi92** [comment]
\o/

**Comment by franziskuskiefer** [comment]
Looks like this is back? At least on Linux with Nightly scrolling is broken again for me.

**Comment by helfi92** [comment]
@franziskuskiefer It's working for me on Nightly with macOS. Could you provide more information perhaps on how I could perhaps replicate.

**Comment by franziskuskiefer** [comment]
@helfi92 right it's working for me on macOS as well. But not on Linux. So this might as well be some Nightly issue. Can you try to reproduce with Nightly on Linux?

**Comment by djmitche** [comment]
I'll try

**Comment by djmitche** [comment]
It works for me -- I just ran the default task from "task creator" which prints 600 digits, one per second, and with "follow log" checked, it indeed follows.

It still has that somehow-incurable horizontal scrollbar covering the last line, but I've given up reporting that issue as it seems to never stay fixed.
