### ISSUE TITLE
Inspector is not auto-updating the state of a task

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-tools#310]
When you have a task that takes a while to resolve for example, the task inspector is not updating the state of that task when it changes. This is not the wanted behavior.

**Comment by djmitche** [comment]
Would adding some console logging help, so that after-the-fact users can copy/paste the contents of the console to help debug?

**Comment by helfi92** [comment]
Sometimes in pages like the task group, there's a lot of event messages being triggered (e.g., new artifact created, new status, etc..). I have a feeling this might cause issues for us when trying to use the web console to develop new features. I personally use a lot of console.log when working on new features and I wouldn't like my web console to be populated. If somehow we could only have those console logs in production, then I'll be happy :)

**Comment by helfi92** [comment]
@eliperelman Any idea why the inspector stops updating sometimes. For some reason, messages from the queue are not being catched anymore. I looked into it but can't seem to figure it out.Btw, this issue seems to happen on the "Task Group" tab as well.

**Comment by eliperelman** [comment]
I'm hoping this gets fixed by #321, we will have to wait and see if this indeed brings resolution.
