### ISSUE TITLE
Make Credentials menu collapse on select

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-tools#311]
In theory, react-bootstrap [supports this now](https://react-bootstrap.github.io/components.html#navbars-mobile-friendly) but in practice, it doesn't seem to work.

You can see the issue by selecting one of the "Sign In" options on the "Sign In" menu.  A new window opens, but if you go back to the original window, there's the menu still hanging out, open.

**Comment by djmitche** [comment]
P.S. don't work on this until http://bugzil.la/1395358 is closed.

**Comment by bessii** [comment]
hello, i would love to work on this issue. Any suggestions on the best way to go about it?

**Comment by eliperelman** [comment]
@bessii hello! To fix this, each of the menu items here needs to close the menu before doing their action:

https://github.com/taskcluster/taskcluster-tools/blob/master/src/components/CredentialsMenu/index.js#L80

**Comment by yash-iiith** [comment]
Hi. I am working on this issue. I added a boolean variable which denotes whether the dropdown menu is opened or not. Initially it is false. When the Sign-in is clicked, its value is toggled and the menu is displayed. When any of the menu item is clicked, I toggle the value of the boolean variable again. But this approach does not seem to work. Please guide me on this.

**Comment by djmitche** [comment]
@yash-iiith it looks like @bessii is already tackling this -- it's usually polite to ask before jumping into a task that someone else is already working on.

That said, it's hard to guide you on what might not work with that approach without seeing the code.  Can you post a PR?

**Comment by yash-iiith** [comment]
@djmitche I apologise for jumping into it.

**Comment by djmitche** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1442937.  @bessii are you still working on this?
