### ISSUE TITLE
Cannot use interactive connect: a.resume is not a function

### ISSUE THREAD

**Issue by Rob--W** [taskcluster/taskcluster-tools#324]
I tried to connect to an interactive task, `https://tools.taskcluster.net/tasks/XXXX/connect`, but I only see an eternally spinning taskcluster logo.

The JS console shows: a.resume is not a function

I stepped through a JS debugger, and found that is caused by this line:

https://github.com/taskcluster/taskcluster-tools/blob/a793bf234447eba782fb5599f45df31374ee5107/src/views/InteractiveConnect/InteractiveConnect.js#L120

Most likely related to #321.

@eliperelman

**Comment by eliperelman** [comment]
Ugh, I'm sorry, I'll get that fixed stat.

**Comment by eliperelman** [comment]
Should go live in about 10 minutes. Thanks for your patience here.

**Comment by Rob--W** [comment]
Thanks for the speedy fix and roll-out. I'm impressed.

**Comment by eliperelman** [comment]
:heart:
