### ISSUE TITLE
Placement of `new hook` and `refresh` in hooks manager

### ISSUE THREAD

**Issue by prachi1210** [taskcluster/taskcluster-tools#337]
In the hooks manager, the option for creating a new hook or refreshing the hooks list moves to the end of the page as new hooks keep getting added and user needs to scroll to the bottom of the page.

<img width="397" alt="hooks manager" src="https://user-images.githubusercontent.com/14016564/31055750-20dba1b0-a6e5-11e7-9e14-aa70ae9814fa.png">

In my opinion, the UI would be more intuitive if the buttons appear on the top.

<img width="321" alt="hooks 2" src="https://user-images.githubusercontent.com/14016564/31055713-cb47208a-a6e4-11e7-8d9d-5262217560f6.png">

@djmitche thoughts?

**Comment by djmitche** [comment]
I agree, but I'd like to hear from @helfi92 or @eliperelman too.

In fact, this is an issue with many of our tools -- client and role editors, secrets, and aws provisioner, to name a few.

**Comment by eliperelman** [comment]
I disagree, but for a different reason. In my mental concepts for a re-designed Tools, I want to have the actions be fixed buttons at the bottom of the screen, where the content scrolls underneath so they are always visible and interactive. This also plays really well with mobile, so actions can be triggered easily using the thumb.

![pic](https://cldup.com/HMBw4mLDqf.png)

**Comment by djmitche** [comment]
It sounds like this isn't a good issue to work on right now, pending the redesign..
