### ISSUE TITLE
Inspector - filtered list of tasks isn't updated

### ISSUE THREAD

**Issue by nthomas-mozilla** [taskcluster/taskcluster-tools#369]
RelEng releaseduty spend time in the inspector to keep an eye on the state of release automation. The status bar seems to keep task counts for each state up to date, but the task list will get out of date. This regressed in the last week or so.

<img width="1153" alt="screen shot" src="https://user-images.githubusercontent.com/942272/32086215-1ee4669e-bb30-11e7-868b-bc6b5a6d90df.png">

Steps to reproduce:
* load a large & active task group, probably anything from a gecko push would be fine
* use the Status filter to select a state which isn't All, eg Running
* do something else while some tasks change state
* observe the task count for the filter has changed, but not the list

Workaround - change the filter to some other value and back again.

**Comment by helfi92** [comment]
Resolved in #371 :)

**Comment by nthomas-mozilla** [comment]
Thanks Hassan.
