### ISSUE TITLE
`taskcluster signìn` integration doesn't extend expiration

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/taskcluster-tools#383]
If the `.../cli` client exists and is expired, it just rotates the accessToken and that's it... The client I get back is still expired..

Note: We do set `deleteOnExpiration`, but I'm pretty sure that `taskcluster-auth` still waits a few days after expiration before deleting clients.

**Comment by djmitche** [comment]
@helfi92 just wrote code to also update the expiration date.  I don't know if that's landed yet, given the change freeze?

**Comment by jonasfj** [comment]
ah, awesome :)

**Comment by djmitche** [comment]
Ah, #381.
