### ISSUE TITLE
Use `slugid` from taskcluster-client-web

### ISSUE THREAD

**Issue by rail** [taskcluster/taskcluster-tools#404]
https://github.com/taskcluster/taskcluster-tools/blob/9121a7fa196fd13ff81af312b6c336675139abb7/src/views/TaskCreator/TaskCreator.js#L5 uses `nice()` from slugid, which is a Node package (it uses Buffer, which is undefined in browsers).

See also https://github.com/taskcluster/taskcluster-client-web/issues/19

**Comment by rail** [comment]
Probably it works because of https://github.com/taskcluster/taskcluster-tools/blob/9121a7fa196fd13ff81af312b6c336675139abb7/.neutrinorc.js#L84, but I'll leave the decision to you.

**Comment by eliperelman** [comment]
This should have been fixed in #407.
