### ISSUE TITLE
AWS-Provisioner work for new spot model

### ISSUE THREAD

**Issue by jhford** [taskcluster/taskcluster-tools#428]
There are a bunch of small changes we should be making to the AWS-Provisioner page.  Not sure if you'd rather have these split into smaller issues, but as they're likely tiny patches it's probably reasonable to do in one PR.

Roughly speaking, spot-requests are no longer tacked anywhere by us, so we should remove them from the UI completely.  Basically, the regexp `[Ss]pot[- ][Rr]equest` should not match anything in the provisioner UI.

The changes are:

1. Remove Spot Requests from the worker-type resources tab.  This table will forever be empty
2. Remove from the bar graphs any mention of spot-request in the tooltip
3. The Spot Request Id column on the worker type resources tab should be removed
4. The worker-type status table should have the requested spot capacity removed

This should only land after Wednesday's EC2-Manager and AWS-Provisioner deployment.

cc @eliperelman @helfi92

**Comment by helfi92** [comment]
@jhford On top of removing any mention of spot requests in the tooltip, I assume you also don't want the bar graphs to show the blue bar (spot request capacity). Can you confirm?

**Comment by jhford** [comment]
> @jhford On top of removing any mention of spot requests in the tooltip, I assume you also don't > want the bar graphs to show the blue bar (spot request capacity). Can you confirm?


> 2. Remove from the bar graphs any mention of spot-request in the tooltip

Yep!

**Comment by helfi92** [comment]
Cool, thanks!
