### ISSUE TITLE
Travis failed to deploy

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-tools#574]
https://travis-ci.org/taskcluster/taskcluster-tools/builds/442179673#L679

**Comment by helfi92** [comment]
@djmitche Are you aware of anything that may have changed?

**Comment by djmitche** [comment]
Nothing I've touched :)

**Comment by djmitche** [comment]
Looks like an auth thing.. maybe check in with @moz-hwine ?
```
checking for app taskcluster-tools
API request failed.
Message: You do not have permission to view on taskcluster-tools. You need to have the view permission on this app.
```

At a guess, maybe Eli was removed, and it was linked under his account?

**Comment by djmitche** [comment]
Yeah, but involves a Heroku API key in a Travis secret.

**Comment by eliperelman** [comment]
This was changed when I left.

https://github.com/taskcluster/taskcluster-tools/commit/e48af3b06e32d33a5191b52ed684606372f16ee8

**Comment by djmitche** [comment]
OK, you're off the hook :)

@helfi92 was that API key deleted or something?

**Comment by helfi92** [comment]
Ahhh, I suspect `helfi92@gmail.com` was disabled access recently because of the transition to SSO login on Heroku. I'll generate a new one.

**Comment by helfi92** [comment]
Hm, actually I'm not sure anymore. The API key is generated via GitHub which has helfi92@gmail.com as my email.
