### ISSUE TITLE
The textarea to edit the trigger context is too small

### ISSUE THREAD

**Issue by marco-c** [taskcluster/taskcluster-tools#578]
It makes it very difficult to see what you're writing.

**Comment by helfi92** [comment]
Could you post a screenshot or a link of the editor you are referring to, please?

**Comment by marco-c** [comment]
Sorry for the lack of details, I assumed there was a single place where you could edit the trigger context :smiley: 

I'm talking about the editor that opens up if you load a hook page (such as https://tools.taskcluster.net/hooks/project-releng/services-staging-codecoverage%2Fbot) and then press "Trigger Hook" at the bottom of the page.

**Comment by helfi92** [comment]
Thanks for elaboring. This is fixed in taskcluster-**web** where the user has the full view to edit the trigger context.

![screen shot 2018-11-07 at 10 36 24 am](https://user-images.githubusercontent.com/3766511/48141521-0fdf1b00-e279-11e8-8e96-2cd15527720f.png)
