### ISSUE TITLE
Two Taskcluster top bars when connecting to a shell

### ISSUE THREAD

**Issue by marco-c** [taskcluster/taskcluster-tools#588]
![screen](https://user-images.githubusercontent.com/1616846/47993600-260d9f80-e0f0-11e8-956d-cab8881749de.png)

**Comment by helfi92** [comment]
I believe this is fixed in taskcluster-web (a rewrite of tc-tools). https://taskcluster-web.netlify.com.

![screen shot 2018-09-25 at 9 34 54 am](https://user-images.githubusercontent.com/3766511/46019264-ac72a280-c0a9-11e8-9b7b-95ce349c92ae.png)

**Comment by helfi92** [comment]
Closing as WONTFIX here since this is fixed in tc-web.
